site_name: AlphaPEM
theme:
  name: readthedocs
  titles_only: true #Only include page titles in the sidebar, excluding all section headers for all pages.

# Plugins used by MkDocs
plugins:
  - search  # Adds a search functionality to the documentation
  - mkdocstrings:  # Uses mkdocstrings to generate documentation from docstrings
      handlers:
        python:  # Uses the Python handler for mkdocstrings
          options:
            docstring_style: numpy  # Uses Numpy style for mkdocstrings

# Structure of the documentation site's navigation
nav:
  - Home: index.md # Documentation home page
  - Functions:
      - GUI: functions/GUI.md
      - Main: functions/main.md
      - Calibration:
          - Experimental values: functions/calibration/experimental_values.md
          - Parameter calibration: functions/calibration/parameter_calibration.md
      - Configuration:
          - Current densities: functions/configuration/current_densities.md
          - Settings: functions/configuration/settings.md
      - Model:
          - AlphaPEM: functions/model/AlphaPEM.md
          - Auxiliaries: functions/model/auxiliaries.md
          - Cell voltage: functions/model/cell_voltage.md
          - Control: functions/model/control.md
          - Differentiel equations: functions/model/dif_eq.md
          - Flows: functions/model/flows.md
      - Modules:
          - Auxiliaries modules: functions/modules/auxiliaries_modules.md
          - Calibration modules: functions/modules/calibration_modules.md
          - Differential equations modules: functions/modules/dif_eq_modules.md
          - Display modules: functions/modules/display_modules.md
          - Flows modules: functions/modules/flows_modules.md
          - GUI modules: functions/modules/GUI_modules.md
          - Main modules: functions/modules/main_modules.md
          - Settings modules: functions/modules/settings_modules.md
          - Transitory functions: functions/modules/transitory_functions.md
  - About: about.md
