# -*- coding: utf-8 -*-

"""
    run_sobol_simulations(cfg, params, all_points)

Run AlphaPEM for all columns of `all_points` and return the resulting polarization curves.

`all_points` is the fused Sobol design matrix (A, B, AB, [BA]) generated by
`GlobalSensitivity.fuse_designs`.

Returns a `DataFrame` with one row per sample containing:
- `sample_id`: integer column index in `all_points`
- parameter columns
- `ifc`: vector of current densities (A/cm²)
- `Ucell`: vector of cell voltages (V)
- `status`: `:ok`, `:failed`, or `:invalid`
"""
function run_sobol_simulations(cfg::SobolAnalysisConfig,
                               params::Vector{InputParameter},
                               all_points::Matrix{Float64})::DataFrame
    n_total = size(all_points, 2)

    # Pre-allocate result containers
    sample_ids = Vector{Int}(undef, n_total)
    ifc_curves = Vector{Union{Vector{Float64}, Nothing}}(undef, n_total)
    Ucell_curves = Vector{Union{Vector{Float64}, Nothing}}(undef, n_total)
    statuses = Vector{Symbol}(undef, n_total)

    # Reference fuel cell and parameters
    base_fc = create_fuelcell(cfg.fuel_cell_type, cfg.voltage_zone; year=cfg.year)
    base_params = base_fc.physical_parameters
    base_oc = base_fc.operating_conditions

    # Numerical params with timeout
    num_params = NumericalParams(
        nb_gc = cfg.numerical_params.nb_gc,
        nb_gdl = cfg.numerical_params.nb_gdl,
        nb_mpl = cfg.numerical_params.nb_mpl,
        nb_man = cfg.numerical_params.nb_man,
        purge_time = cfg.numerical_params.purge_time,
        delta_purge = cfg.numerical_params.delta_purge,
        delta_t_dyn_step = cfg.numerical_params.delta_t_dyn_step,
        rtol = cfg.numerical_params.rtol,
        atol = cfg.numerical_params.atol,
        maxiters = cfg.numerical_params.maxiters,
        max_run_time_s = cfg.max_run_time_s,
        save_freq = cfg.numerical_params.save_freq
    )

    # Warm-up compilation
    @info "Pre-warming AlphaPEM compilation..."
    _warm_up_sobol_simulation(cfg, params, base_params, base_oc)

    @info "Running $(n_total) Sobol simulations..."
    prog = Progress(n_total; desc = "Sobol simulations: ", barlen = 40, color = :cyan)

    if cfg.parallel && Threads.nthreads() > 1
        BLAS.set_num_threads(1)
        prog_lock = ReentrantLock()
        Threads.@threads for i in 1:n_total
            sample = all_points[:, i]
            status, ifc, Ucell = _run_one_sobol_sample(
                sample, params, cfg, base_params, base_oc, num_params
            )

            sample_ids[i] = i
            statuses[i] = status
            ifc_curves[i] = ifc
            Ucell_curves[i] = Ucell

            lock(prog_lock) do
                next!(prog)
            end
        end
    else
        for i in 1:n_total
            sample = all_points[:, i]
            status, ifc, Ucell = _run_one_sobol_sample(
                sample, params, cfg, base_params, base_oc, num_params
            )

            sample_ids[i] = i
            statuses[i] = status
            ifc_curves[i] = ifc
            Ucell_curves[i] = Ucell

            next!(prog)
        end
    end
    finish!(prog)

    # Build DataFrame
    df = DataFrame()
    df.sample_id = sample_ids
    df.status = statuses

    for (j, p) in enumerate(params)
        df[!, p.name] = all_points[j, :]
    end

    df.ifc = ifc_curves
    df.Ucell = Ucell_curves

    # Save raw curves if requested
    if cfg.save_curves
        curves_path = joinpath(cfg.output_dir, "raw_curves.csv")
        mkpath(dirname(curves_path))
        _save_raw_curves(curves_path, sample_ids, ifc_curves, Ucell_curves, statuses)
    end

    return df
end


"""
    _save_raw_curves(filepath, sample_ids, ifc_curves, Ucell_curves, statuses)

Save raw polarization curves to a CSV file.
"""
function _save_raw_curves(filepath::String,
                          sample_ids::Vector{Int},
                          ifc_curves::Vector{Union{Vector{Float64}, Nothing}},
                          Ucell_curves::Vector{Union{Vector{Float64}, Nothing}},
                          statuses::Vector{Symbol})
    rows = []
    for i in 1:length(sample_ids)
        ifc = ifc_curves[i]
        Ucell = Ucell_curves[i]
        if ifc === nothing || Ucell === nothing
            push!(rows, (
                sample_id = sample_ids[i],
                current_density = missing,
                voltage = missing,
                status = string(statuses[i])
            ))
        else
            for (i_val, u_val) in zip(ifc, Ucell)
                push!(rows, (
                    sample_id = sample_ids[i],
                    current_density = i_val,
                    voltage = u_val,
                    status = string(statuses[i])
                ))
            end
        end
    end
    CSV.write(filepath, DataFrame(rows))
    return nothing
end


"""
    _run_one_sobol_sample(sample, params, cfg, base_params, base_oc, num_params)

Run AlphaPEM for a single Sobol sample and extract the polarization curve.

Returns `(status, ifc, Ucell)` where `status` is `:ok`, `:failed`, or `:invalid`.
Current densities are returned in A/cm².
"""
function _run_one_sobol_sample(sample::Vector{Float64},
                               params::Vector{InputParameter},
                               cfg::SobolAnalysisConfig,
                               base_params,
                               base_oc,
                               num_params::NumericalParams)
    try
        # Build modified physical parameters and operating conditions
        physical_params = sample_to_physical_params(sample, params, base_params)
        operating_conditions = sample_to_operating_conditions(
            sample, params, base_oc,
            cfg.operating_condition_constraints,
            cfg.excluded_operating_conditions
        )

        # Build fuel cell
        fc = create_fuelcell(cfg.fuel_cell_type, cfg.voltage_zone; year=cfg.year)
        fc.physical_parameters = physical_params
        fc.operating_conditions = operating_conditions

        # Validate operating conditions
        if !is_valid_operating_conditions(operating_conditions)
            return (:failed, nothing, nothing)
        end

        # Build simulation config
        sim_cfg = SimulationConfig(
            type_fuel_cell = cfg.fuel_cell_type,
            year = cfg.year,
            type_current = cfg.polarization_params,
            numerical_parameters = num_params,
            voltage_zone = cfg.voltage_zone,
            type_display = :no_display,
            display_timing = :postrun,
            physical_parameters = physical_params,
            operating_conditions = operating_conditions
        )

        # Run simulation
        cd = create_current(cfg.polarization_params, fc)
        simu = AlphaPEMSimulator(fc, cd, sim_cfg)
        simulate_model!(simu)

        # Extract polarization points
        if simu.outputs === nothing
            return (:failed, nothing, nothing)
        end

        ifc_raw, Ucell_raw = _polarization_points(simu.outputs, simu.current_density; average = true)
        if isempty(ifc_raw) || isempty(Ucell_raw)
            return (:invalid, nothing, nothing)
        end

        # Convert current density from A/m² to A/cm²
        ifc_cm2 = ifc_raw ./ 1e4

        # Basic validity check
        if any(!isfinite, Ucell_raw) || any(!isfinite, ifc_cm2)
            return (:invalid, nothing, nothing)
        end

        return (:ok, ifc_cm2, Ucell_raw)

    catch e
        return (:failed, nothing, nothing)
    end
end


"""
    _warm_up_sobol_simulation(cfg, params, base_params, base_oc)

Run a single throwaway simulation to trigger JIT compilation.
"""
function _warm_up_sobol_simulation(cfg::SobolAnalysisConfig,
                                   params::Vector{InputParameter},
                                   base_params,
                                   base_oc)
    try
        sample = Float64[(p.min + p.max) / 2 for p in params]
        num_params = NumericalParams(
            nb_gc = cfg.numerical_params.nb_gc,
            nb_gdl = cfg.numerical_params.nb_gdl,
            nb_mpl = cfg.numerical_params.nb_mpl,
            nb_man = cfg.numerical_params.nb_man,
            purge_time = cfg.numerical_params.purge_time,
            delta_purge = cfg.numerical_params.delta_purge,
            delta_t_dyn_step = cfg.numerical_params.delta_t_dyn_step,
            rtol = cfg.numerical_params.rtol,
            atol = cfg.numerical_params.atol,
            maxiters = cfg.numerical_params.maxiters,
            max_run_time_s = cfg.max_run_time_s,
            save_freq = cfg.numerical_params.save_freq
        )
        _run_one_sobol_sample(sample, params, cfg, base_params, base_oc, num_params)
    catch
        # Ignore warm-up errors
    end
    return nothing
end
