# -*- coding: utf-8 -*-

"""
    run_sobol_simulations(cfg, params, all_points)

Run AlphaPEM for all columns of `all_points` and return the resulting polarization curves.

`all_points` is the fused Sobol design matrix (A, B, AB, [BA]) generated by
`GlobalSensitivity.fuse_designs`.

Returns a `DataFrame` with one row per sample containing:
- `sample_id`: integer column index in `all_points`
- parameter columns
- `ifc`: vector of current densities (A/cm²)
- `Ucell`: vector of cell voltages (V)
- `status`: `:ok`, `:failed`, or `:invalid`
"""
function run_sobol_simulations(cfg::SobolAnalysisConfig,
                               params::Vector{InputParameter},
                               all_points::Matrix{Float64};
                               df_existing::Union{DataFrame, Nothing} = nothing,
                               on_checkpoint::Union{Function, Nothing} = nothing)::DataFrame
    n_total = size(all_points, 2)
    missing_ids = _find_missing_sample_ids(df_existing, n_total)
    n_missing = length(missing_ids)

    # Pre-allocate result containers (indexed by sample_id)
    sample_ids = Vector{Int}(undef, n_total)
    ifc_curves = Vector{Union{Vector{Float64}, Nothing}}(undef, n_total)
    Ucell_curves = Vector{Union{Vector{Float64}, Nothing}}(undef, n_total)
    statuses = Vector{Symbol}(undef, n_total)

    # Track which sample_ids are complete to avoid serialising undefined entries
    completed_ids = Int[]

    # Restore already-completed samples from a previous checkpoint
    if df_existing !== nothing && nrow(df_existing) > 0
        sizehint!(completed_ids, n_total)
        for row in eachrow(df_existing)
            sid = row.sample_id
            sample_ids[sid] = sid
            statuses[sid] = row.status
            ifc_curves[sid] = row.ifc
            Ucell_curves[sid] = row.Ucell
            push!(completed_ids, sid)
        end
    end

    # Reference fuel cell and parameters
    base_fc = create_fuelcell(cfg.fuel_cell_type, cfg.voltage_zone; year=cfg.year)
    base_params = base_fc.physical_parameters
    base_oc = base_fc.operating_conditions

    # Numerical params with timeout
    num_params = NumericalParams(
        nb_gc = cfg.numerical_params.nb_gc,
        nb_gdl = cfg.numerical_params.nb_gdl,
        nb_mpl = cfg.numerical_params.nb_mpl,
        nb_man = cfg.numerical_params.nb_man,
        purge_time = cfg.numerical_params.purge_time,
        delta_purge = cfg.numerical_params.delta_purge,
        delta_t_dyn_step = cfg.numerical_params.delta_t_dyn_step,
        rtol = cfg.numerical_params.rtol,
        atol = cfg.numerical_params.atol,
        maxiters = cfg.numerical_params.maxiters,
        max_run_time_s = cfg.max_run_time_s,
        save_freq = cfg.numerical_params.save_freq
    )

    # Warm-up compilation
    @info "Pre-warming AlphaPEM compilation..."
    _warm_up_sobol_simulation(cfg, params, base_params, base_oc)

    if n_missing == 0
        @info "All $(n_total) Sobol simulations already completed in checkpoint."
    else
        @info "Running $(n_missing) missing Sobol simulations ($(n_total - n_missing) already done)..."
    end
    prog = Progress(n_missing; desc = "Sobol simulations: ", barlen = 40, color = :cyan)

    completed_since_start = 0
    checkpoint_lock = ReentrantLock()

    function store_result!(sid::Int, status::Symbol, ifc, Ucell)
        lock(checkpoint_lock) do
            sample_ids[sid] = sid
            statuses[sid] = status
            ifc_curves[sid] = ifc
            Ucell_curves[sid] = Ucell
            push!(completed_ids, sid)
            completed_since_start += 1

            if cfg.checkpoint_frequency > 0 &&
               completed_since_start % cfg.checkpoint_frequency == 0 &&
               on_checkpoint !== nothing
                df_partial = _build_curves_df(
                    completed_ids, sample_ids, statuses, ifc_curves, Ucell_curves,
                    all_points, params, n_total
                )
                on_checkpoint(df_partial)
            end
        end
    end

    if cfg.parallel && Threads.nthreads() > 1
        BLAS.set_num_threads(1)
        prog_lock = ReentrantLock()
        Threads.@threads for i in 1:n_missing
            sid = missing_ids[i]
            sample = all_points[:, sid]
            status, ifc, Ucell = _run_one_sobol_sample(
                sample, params, cfg, base_params, base_oc, num_params
            )
            store_result!(sid, status, ifc, Ucell)
            lock(prog_lock) do
                next!(prog)
            end
        end
    else
        for i in 1:n_missing
            sid = missing_ids[i]
            sample = all_points[:, sid]
            status, ifc, Ucell = _run_one_sobol_sample(
                sample, params, cfg, base_params, base_oc, num_params
            )
            store_result!(sid, status, ifc, Ucell)
            next!(prog)
        end
    end
    finish!(prog)

    # Build full DataFrame from all completed rows
    sort!(completed_ids)
    df = _build_curves_df(
        completed_ids, sample_ids, statuses, ifc_curves, Ucell_curves,
        all_points, params, n_total
    )

    # Save raw curves if requested
    if cfg.save_curves
        curves_path = joinpath(cfg.output_dir, "raw_curves.csv")
        mkpath(dirname(curves_path))
        _save_raw_curves(curves_path, sample_ids, ifc_curves, Ucell_curves, statuses)
    end

    return df
end


"""
    _build_curves_df(completed_ids, sample_ids, statuses, ifc_curves, Ucell_curves, all_points, params, n_total)

Assemble the per-sample result arrays into a DataFrame for the completed sample ids.

`completed_ids` contains the indices that have been simulated; only those rows are
included in the returned DataFrame, avoiding any undefined entries in the sparse
arrays.
"""
function _build_curves_df(completed_ids::Vector{Int},
                          sample_ids::Vector{Int},
                          statuses::Vector{Symbol},
                          ifc_curves::Vector{Union{Vector{Float64}, Nothing}},
                          Ucell_curves::Vector{Union{Vector{Float64}, Nothing}},
                          all_points::Matrix{Float64},
                          params::Vector{InputParameter},
                          n_total::Int)::DataFrame
    df = DataFrame()
    df.sample_id = sample_ids[completed_ids]
    df.config_hash = [_hash_sample(all_points[:, sid]) for sid in completed_ids]
    df.status = statuses[completed_ids]

    for (j, p) in enumerate(params)
        df[!, p.name] = all_points[j, completed_ids]
    end

    df.ifc = ifc_curves[completed_ids]
    df.Ucell = Ucell_curves[completed_ids]

    return df
end


"""
    _save_raw_curves(filepath, sample_ids, ifc_curves, Ucell_curves, statuses)

Save raw polarization curves to a CSV file.
"""
function _save_raw_curves(filepath::String,
                          sample_ids::Vector{Int},
                          ifc_curves::Vector{Union{Vector{Float64}, Nothing}},
                          Ucell_curves::Vector{Union{Vector{Float64}, Nothing}},
                          statuses::Vector{Symbol})
    rows = []
    for i in 1:length(sample_ids)
        ifc = ifc_curves[i]
        Ucell = Ucell_curves[i]
        if ifc === nothing || Ucell === nothing
            push!(rows, (
                sample_id = sample_ids[i],
                current_density = missing,
                voltage = missing,
                status = string(statuses[i])
            ))
        else
            for (i_val, u_val) in zip(ifc, Ucell)
                push!(rows, (
                    sample_id = sample_ids[i],
                    current_density = i_val,
                    voltage = u_val,
                    status = string(statuses[i])
                ))
            end
        end
    end
    CSV.write(filepath, DataFrame(rows))
    return nothing
end


"""
    _run_one_sobol_sample(sample, params, cfg, base_params, base_oc, num_params)

Run AlphaPEM for a single Sobol sample and extract the polarization curve.

Returns `(status, ifc, Ucell)` where `status` is `:ok`, `:failed`, or `:invalid`.
Current densities are returned in A/cm².
"""
function _run_one_sobol_sample(sample::Vector{Float64},
                               params::Vector{InputParameter},
                               cfg::SobolAnalysisConfig,
                               base_params,
                               base_oc,
                               num_params::NumericalParams)
    try
        # Build modified physical parameters and operating conditions
        physical_params = sample_to_physical_params(sample, params, base_params)
        operating_conditions = sample_to_operating_conditions(
            sample, params, base_oc,
            cfg.operating_condition_constraints,
            cfg.excluded_operating_conditions
        )

        # Build fuel cell
        fc = create_fuelcell(cfg.fuel_cell_type, cfg.voltage_zone; year=cfg.year)
        fc.physical_parameters = physical_params
        fc.operating_conditions = operating_conditions

        # Validate operating conditions
        if !is_valid_operating_conditions(operating_conditions, cfg.operating_condition_constraints)
            return (:failed, nothing, nothing)
        end

        # Build simulation config
        sim_cfg = SimulationConfig(
            type_fuel_cell = cfg.fuel_cell_type,
            year = cfg.year,
            type_current = cfg.polarization_params,
            numerical_parameters = num_params,
            voltage_zone = cfg.voltage_zone,
            type_display = :no_display,
            display_timing = :postrun,
            physical_parameters = physical_params,
            operating_conditions = operating_conditions
        )

        # Run simulation
        cd = create_current(cfg.polarization_params, fc)
        simu = AlphaPEMSimulator(fc, cd, sim_cfg)
        simulate_model!(simu)

        # Extract polarization points
        if simu.outputs === nothing
            return (:failed, nothing, nothing)
        end

        ifc_raw, Ucell_raw = _polarization_points(simu.outputs, simu.current_density; average = true)
        if isempty(ifc_raw) || isempty(Ucell_raw)
            return (:invalid, nothing, nothing)
        end

        # _polarization_points already returns current densities in A/cm²
        ifc_cm2 = ifc_raw

        # Basic validity check
        if any(!isfinite, Ucell_raw) || any(!isfinite, ifc_cm2)
            return (:invalid, nothing, nothing)
        end

        return (:ok, ifc_cm2, Ucell_raw)

    catch e
        return (:failed, nothing, nothing)
    end
end


"""
    _warm_up_sobol_simulation(cfg, params, base_params, base_oc)

Run a single throwaway simulation to trigger JIT compilation.
"""
function _warm_up_sobol_simulation(cfg::SobolAnalysisConfig,
                                   params::Vector{InputParameter},
                                   base_params,
                                   base_oc)
    try
        sample = Float64[(p.min + p.max) / 2 for p in params]
        num_params = NumericalParams(
            nb_gc = cfg.numerical_params.nb_gc,
            nb_gdl = cfg.numerical_params.nb_gdl,
            nb_mpl = cfg.numerical_params.nb_mpl,
            nb_man = cfg.numerical_params.nb_man,
            purge_time = cfg.numerical_params.purge_time,
            delta_purge = cfg.numerical_params.delta_purge,
            delta_t_dyn_step = cfg.numerical_params.delta_t_dyn_step,
            rtol = cfg.numerical_params.rtol,
            atol = cfg.numerical_params.atol,
            maxiters = cfg.numerical_params.maxiters,
            max_run_time_s = cfg.max_run_time_s,
            save_freq = cfg.numerical_params.save_freq
        )
        _run_one_sobol_sample(sample, params, cfg, base_params, base_oc, num_params)
    catch
        # Ignore warm-up errors
    end
    return nothing
end


"""
    _hash_sample(sample)

Return a SHA-256 hex digest of a sample vector.

This provides a reproducible, content-based identifier for each row of the Sobol
design matrix, enabling traceability and deduplication across plan, simulations
and outputs.
"""
function _hash_sample(sample::AbstractVector{<:Real})::String
    bytes = Vector{UInt8}(join(string.(sample), ","))
    return bytes2hex(sha256(bytes))
end
